<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30186" started-at="2023-03-09T15:45:09Z" finished-at="2023-03-09T15:45:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30186" started-at="2023-03-09T15:45:09Z" finished-at="2023-03-09T15:45:40Z">
      <class name="restAssured.HttpMethods">
        <test-method status="PASS" signature="getMethod()[pri:0, instance:restAssured.HttpMethods@7d68ef40]" name="getMethod" duration-ms="16192" started-at="2023-03-09T15:45:10Z" finished-at="2023-03-09T15:45:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getMethod -->
        <test-method status="PASS" signature="patchMethod()[pri:0, instance:restAssured.HttpMethods@7d68ef40]" name="patchMethod" duration-ms="6219" started-at="2023-03-09T15:45:26Z" finished-at="2023-03-09T15:45:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- patchMethod -->
        <test-method status="PASS" signature="postMethod()[pri:0, instance:restAssured.HttpMethods@7d68ef40]" name="postMethod" duration-ms="1914" started-at="2023-03-09T15:45:32Z" finished-at="2023-03-09T15:45:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postMethod -->
        <test-method status="PASS" signature="putMethod()[pri:0, instance:restAssured.HttpMethods@7d68ef40]" name="putMethod" duration-ms="1874" started-at="2023-03-09T15:45:34Z" finished-at="2023-03-09T15:45:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putMethod -->
        <test-method status="FAIL" signature="queryParamTest()[pri:0, instance:restAssured.HttpMethods@7d68ef40]" name="queryParamTest" duration-ms="2996" started-at="2023-03-09T15:45:36Z" finished-at="2023-03-09T15:45:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [300] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [300] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restAssured.HttpMethods.queryParamTest(HttpMethods.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- queryParamTest -->
      </class> <!-- restAssured.HttpMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
